### PR TITLE
Extend ExcelReference constructor

### PR DESCRIPTION
**Pull request by n1l**
Issue with details - https://github.com/Excel-DNA/ExcelDna/issues/286

### CODE REVIEW

**Comment by govert** [comment]
Thanks for this.

* I think we should add a check and throw an exception if the SheetIds are not all the same.

* Where do you get the ExcelReferences that make this a useful override for you?

**Comment by n1l** [comment]
We had a performance issue while changing cell format, so we create some code to cache references before format changing to improve performance.

**Comment by n1l** [comment]
About exception, the code is basically copied from another c'tor with array in params, so in the code we use only rectangle values from references, and the sheetId is the same.

**Comment by govert** [comment]
Since an ExcelReference refers to a range on a particular sheet, I think it would be a mistake to send in ExcelReferences that refer to different sheets (since the compound ExcelReference cannot support these). So I suggest we:
* Change the signature to only be 
`public ExcelRefernece(IEnumerable<ExcelReference> references)`
* Throw an `ArgumentException` if there are different SheetIds among the references, and use the unique `SheetId` for the `ExcelReference` we're constructing.

An alternative would be a static helper on the `ExcelReference` class like
`public static IEnumerable<ExcelReference> UnionPerSheet(IEnumerable<ExcelReference> references)`
that groups per `SheetId` and returns a compound `ExcelReference` for each `SheetId'. I'm not sure whether that's better, and in any case a utility library in the add-in can do this easily too.

**Comment by n1l** [comment]
I see, I think you're right. I've updated c'tor.

**Pull request merged**
