### PR TITLE
* add /NC option (no Compression) for packing without lzma

### PR DESCRIPTION
**Pull request by konne**
if you have big projects the packing can take a long time, for testing if packing is working fine the version without LZMA is much faster (like my project 40sec. -> 3sec.)

There is a new commad line parameter /NC -> this means no compression

Signed-off-by: Konrad Mattheis <konrad.mattheis@akquinet.de>

### CODE REVIEW

**Comment by konne** [comment]
Hi govert,

I also added the mutlithreading for the lzma compression. This reduce the packing time for my project to the half.

please check and give me a feedback.

**Comment by govert** [comment]
Hi Konrad,

I'm happy with the suggestion, but will have to go through the code changes.
Could you maybe suggest a different name for the flag? I'd prefer something more descriptive than /NC

-Govert

**Comment by konne** [comment]
Hi Govert

- flag Ideas: /no_lzma /nolzma, better?

-SevenZipHelper: yes, because the compression properties are static defined, I already testing this changes sinces about 3month with no issue.

bye
Konrad

**Comment by govert** [comment]
What about /NoCompression ?
(I'm also tempted to suggest /NoDepression)

If we manage to refactor the build process a bit more, as started in #27  this could become an option in the ExcelDna.Build.props file.

---
I'm a bit unsure about using the enum .ToString() values directly.
Could you at least add some comments to the enum that indicates that the values are used this way, and that the names cannot be changed.

Also, where AddFile is called with the compression option always set to false (e.g. for .config files) we should note that this cannot be changed without changing the usage inside the native code or ExcelDna.Loader.

**Comment by govert** [comment]
Multithreaded compression:

Would it be a good idea to keep all the resource updates on the same thread (they're serialized with a lock anyway) and just have the compression be done on the worker threads?
That might require a bit more bookkeeping for the threadpool tasks, but would get rid of the worker threads running in other parts of the ResourceHelper code.

I'm also a bit by the non-determinism we're introducing by the update sequence not always being the same. Is there a way to get the resource update sequence always be the same, even though the compression tasks might run in parallel?

**Comment by konne** [comment]
>What about /NoCompression ?
okay, I change it.

>BuildTasks, I have seen this, and this is also a later task for me to make a real msbuildtask out of the ExcelDNAPack, so you don't have to call it via <Exec...>

>I'm a bit unsure about using the enum .ToString() values directly,...
I will comment this and have the plan to move this at a general level. I used already the same "ids / numbers" what you are using in the .Loader. I suggest to change "internal static byte[] GetResourceBytes@AssemblyManager.cs", the type = 0. If the enum is general in a later step this code can also change.

**Comment by konne** [comment]
>Multithreaded compression
It is really faster if we update the resource in a separate thread. Even if it has to wait sometimes a little bit, because of the lock. 
The sequence of updating the resources has no effect. For all resources that are accessed by "name" I see nothing. The only point is that typelib resources can have a different typelib number.
I can change that point, but the code is than more complex and need more memory, because we have to make a byet[] -> list of all compressed resources and update this after all compression is done.

**Comment by konne** [comment]
FYI, I also working on a bigger change (http://exceldna.codeplex.com/discussions/632029#post1416974) but with the real usage of the build in localisation feature of FindResourceEx,... and not the first working but not so nice approach from my codeplex discussion.

**Comment by govert** [comment]
OK - we'll try it with the multi-threaded resource updates, and if there issues we can add a switch to do a deterministic single-threading pack.

**Comment by govert** [comment]
Can you explain about the TypeLib resources?

**Comment by konne** [comment]
every time you add a Typelib, you increase the typelibnumber and add each typelib only with a number as reference. 
>ResourceHelper.UpdateResource(_hUpdate, typeName, (IntPtr)typelibIndex, localeNeutral, pinHandle.AddrOfPinnedObject(), (uint)data.Length);

So It could be happen that typelibs get different numbers, because of different calling of the adding.
But I never saw that anybody was complaining that he has to change the ordering of the references in the DNA file.

**Comment by konne** [comment]
Hi Govert,

I have changed the NC to /NoCompression.
Could you already test the multithreading of lzma, did you find any problems?

bye
Konrad

**Comment by govert** [comment]
@konne I have not tried it yet.

I'll check it, and if all looks OK, I'll accept to pull request.
I might then add a new Issue for us to consider maybe adding another flag that forces a deterministic (single-threaded build). The issue would serve as a reminder that this is something to look out for, if anyone else is bothered by the new behaviour.

**Comment by konne** [comment]
No Problem, I will add another Command Line Parameter /NoMultiThreaded okay for the naming?
Stopping the Multithreading is very easy :-)

**Comment by govert** [comment]
OK cool - that would be great. I guess "NoMultiThreading" is better than "NoMultiThreaded".

**Comment by konne** [comment]
Features is added, please test and add to the mainline

**Comment by govert** [comment]
@konne I've changed the CLA handler to CLA assistant since CLA Hub is not working anymore.
I can't really see what the experience is from your perspective.

You should have seen a prompt when updating the other PR. If there's a problem, please let me know.

Otherwise, I'm happy to accept this PR - in my (fairly quick) tests it worked fine.

**Comment by konne** [comment]
I got an CLA email and I accepted the rules

**Comment by konne** [comment]
it is stranged I accept the cla and the system says, thank you for accepting and than the cla is still not okay

**Comment by govert** [comment]
@konne I can see that you agreed to the CLA. Not sure why it didn't pick it up.

Thank you very much for your contribution to making Excel-DNA better!

**Pull request merged**
