### PR TITLE
Fix ExcelDnaPack crashing due to unhandled exceptions | fixes #25

### LINKED ISSUE #25: ExcelDnaPack crashes during build - needs to catch exceptions before MSBuild does
When an unhandled exception occurs in `ExcelDnaPack`, it lets it bubble up to the caller, and crashes. This causes MSBuild/Visual Studio to show the dialogs below:

pack-error-01
pack-error-02

We need to catch any unhandled exceptions in Main, and return a Environment.ExitCode >= 1 to signal that it failed - so that MSBuild can fail the build too.

### PR DESCRIPTION
**Pull request by CaioProiete**

### CODE REVIEW

**Comment by govert** [comment]
The last time I fixed up the exit codes, if was just a quick fix and never properly cleaned up. Instead of just adding the exception handler, I'd prefer if we can at least clean up a bit too. I suggest:

* Your new Pack method should rather return some result code (maybe a new enum) from all the `return;` exit locations, and not set `Environment.ExitCode` itself. 

* Then the new Main becomes the only place where the process exit code is set. There are some places which call `Environment.Exit(1)`. These should probably throw an exception, which will be caught and displayed in Main.

* We must decide on the result codes returned from the process. At the moment it seems like a mix of -1, 0 and 1. I don't have a strong opinion on whether all error just return 1 (or -1), or whether we return different error codes. But the current mix of sometime returning -1 and sometimes 1 for the error seems weird. I'd be OK with all error conditions returning 1, if you think that makes sense.

**Comment by CaioProiete** [comment]
@govert: Absolutely agree with all the points above, but I'm currently working on #17 (made great progress today BTW, expect to have a PR tomorrow), and `ExcelDnaPack` crashing is a blocker as I cannot reliably fail the build when something goes wrong.

This PR does the bare minimum change to fix the issue, without introducing any breaking changes - so it actually makes things better than it is today / moves us forward.

I'd prefer you merge this one as is, and open a new issue for improving `ExcelDnaPack` exception handling, and we can revisit this later (likely as part of #15).

**Comment by govert** [comment]
OK - then let's put all of it into a temporary branch, at least until I'm done with v0.33. Maybe "build-targets" or something.
Do I need to make the branch, or can you do that as part of the Pull Requests?

**Comment by CaioProiete** [comment]
Great.

I don't have write permission on the main repo, so you'll have to create the branch. I can only open pull-requests for existing branches.

**Comment by govert** [comment]
Done.

**Pull request merged**
