### PR TITLE
Added packing native libraries from .deps.json and resolving them at runtime

### PR DESCRIPTION
**Pull request by Sergey-Vlasov**
1. Increased ExcelDna.AddIn.Tasks project's target framework from net452 to net462.

2. I couldn't find a way to clean the temp directory as there are no unloading events available in ExcelDna.ManagedHost.

### CODE REVIEW

**Comment by govert** [comment]
1. Would it make sense to use a stable guid for the temp directory where we extract ExcelDna.ManagedHost.dll and the native libraries? We have a stable guid per add-in, derived from the add-in path, which is used in the IntelliSense. See https://github.com/Excel-DNA/RegistrationInfoGuid and https://github.com/Excel-DNA/ExcelDna/blob/master/Source/ExcelDna.Integration/GuidUtility.cs

2. In addition to the native libraries, I'm hoping we can add the managed platform-specific libraries from the .deps.json file into the ExcelDnaPack list as well. Thus that the example add-in would work without an `<ExcelAddInInclude>` property in the project file. It would select the platform specific version of System.Management for packing in a similar way.  I think the Microsoft.Data.SqlClient package, or an EFCore package, has both native and platform specific managed dependencies. Do you want to add this as part of this PR, or a separate PR and have me pull this first? I'm happy either way.

3. Do you think we need a property or similar to control this behaviour of that packing task and opt out if needed?

**Comment by govert** [comment]
4. Do you think we need a property to exclude specific file(s) from the deps.json-based packing?

**Comment by Sergey-Vlasov** [comment]
1. With a stable guid, it will not be a temp dir, but an add-in storage dir. With a different design and two implementations for C++ and C# code.

**Comment by Sergey-Vlasov** [comment]
2. A separate PR. I expect automatically packing managed libraries will be a major (breaking?) change in user experience for a packed add-in.

**Comment by Sergey-Vlasov** [comment]
3,4. I've added ExcelDnaPackNativeLibraryDependencies and ExcelDnaPackExcludeDependencies project properties.

**Comment by govert** [comment]
I suggest we call it ExcelDnaPackDependencies (with default true) instead of ExcelDnaPackNativeLibraryDependencies, and use that for both the managed and native dependencies.

**Comment by Sergey-Vlasov** [comment]
I’m still uncertain about packing managed dependencies. First, .deps.json is imprecise in specifying managed dependencies. And then it has to be integrated with existing managed packing options. 

I thought about a second ExcelDnaPackManagedDependencies option.

**Comment by govert** [comment]
OK - we can keep two properties then, and see how the managed dependencies work as a separate PR.

The way I think about it is that we if PackxxxDependencies is enabled, then we pack the managed and native dependencies from .deps.json, plus any files in ExcelAddInInclude minus any files in ExcelDnaPackExcludeDependencies.
So that by default an add-in author can add NuGet packages, and build, and the packed file will have everything - managed and native.

**Comment by Sergey-Vlasov** [comment]
Should I set default true for ExcelDnaPackNativeLibraryDependencies?

**Comment by Sergey-Vlasov** [comment]
I've set default true for ExcelDnaPackNativeLibraryDependencies.

**Comment by govert** [comment]
> I couldn't find a way to clean the temp directory as there are no unloading events available in ExcelDna.ManagedHost.

Do I understand right that this means every run of the add-in will create a new directory with the files in?
That's way I asked about the stable directory.

> With a stable guid, it will not be a temp dir, but an add-in storage dir. With a different design and two implementations for C++ and C# code.

I want to see how this works first, so can you change the default back to false for ExcelDnaPackNativeLibraryDependencies?

**Comment by govert** [comment]
> > With a stable guid, it will not be a temp dir, but an add-in storage dir. With a different design and two implementations for C++ and C# code.

> I want to see how this works first, so can you change the default back to false for ExcelDnaPackNativeLibraryDependencies?

I mean I just want to try the current implementation first, not that we should do the storage dir yet.

**Comment by Sergey-Vlasov** [comment]
> Do I understand right that this means every run of the add-in will create a new directory with the files in?

Yes.

**Comment by Sergey-Vlasov** [comment]
> I want to see how this works first, so can you change the default back to false for ExcelDnaPackNativeLibraryDependencies?

Done.

**Pull request merged**
