### PR TITLE
Fix for issue #45

### PR DESCRIPTION
**Pull request by alainbryden**
Proposed fix for https://github.com/Excel-DNA/ExcelDna/issues/45#issuecomment-154597865

### CODE REVIEW

**Comment by govert** [comment]
Cool @alainbryden  - thank you!
Should we do the same for functionDescription, as few lines down?

**Comment by alainbryden** [comment]
Hmm, yes I think so. I had ignored it because at a glance I thought it only applied when the description was empty, but it looks like it will run when there are no function arguments but the description is non-empty.

**Comment by alainbryden** [comment]
Pushed and squashed additional fix.

**Comment by govert** [comment]
Thanks Alain!

**Pull request merged**
