### PR TITLE
log RTD COM server init errors - fix #224

### LINKED ISSUE #224: Diagnostic log doesn't log persistent RTD server init errors
https://github.com/fandrei/RtdMinimal
The constructor or RtdServerMinimal throws an exception, but it's not written to the diag log.

### PR DESCRIPTION
**Pull request by fandrei**

### CODE REVIEW

**Comment by fandrei** [comment]
@govert  Hmm. How do I view the failed ci build log?

**Comment by govert** [comment]
Ignore - it's not working at the moment

**Comment by fandrei** [comment]
@govert ok. Basically, I just added a try/catch and log reporting to the code that creates a persistent RTD COM server object, as this code wasn't handling exceptions before.

**Comment by govert** [comment]
Cool - thanks @fandrei

**Pull request merged**
